# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Tabman'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'NMapsMap'
  # Pods for MovieAPI

end
